install_dependencies:
	cd ./frontend && pnpm install
	cd ./backend && pnpm install

run_frontend:
	cd ./frontend && pnpm run dev

run_backend:
	cd ./backend && pnpm run develop


build_frontend:
	cd ./frontend && pnpm run build

build_backend:
	cd ./backend && pnpm run build
